### ISSUE TITLE
compilation with ghc 8.8.2 stack 15.1

### ISSUE THREAD

**Issue by zemanlx** [hadolint/language-docker#49]
I am trying to get our hadolint/hadolint working with the latest LTS stack. Unfortunately, build is failing for this repo with the latest `stack 15.1` which is using `ghc 8.8.2` and I am getting this error:

```haskell
/home/zemanlx/git/language-docker/src/Language/Docker/Syntax/Lift.hs:18:10: error:
    Duplicate instance declarations:
      instance Lift Text.Text
        -- Defined at src/Language/Docker/Syntax/Lift.hs:18:10
      instance Lift Text.Text -- Defined in ‘Data.Text’
   |
18 | instance Lift Text.Text where
   |          ^^^^^^^^^^^^^^
```

I bet it is something that can be solved somehow trivially but I do not know how. If I can get hint @lorenzo I am happy to make PR for it.

**Comment by lorenzo** [comment]
Yeah, good timing, I'm actually working on this on my spare time. I can submit the fix for this already if you like.

The consequence is that the package will only compile in `GHC >= 8.8` which is probably not an issue. What do you think?

**Comment by zemanlx** [comment]
That sounds great! I am fine if we can compile a new version with 8.8+ only. If you can make a fix just for this it would be perfect.

**Comment by lorenzo** [comment]
I'll push it today

**Comment by zemanlx** [comment]
closed in #50
