### ISSUE TITLE
src/Language/Docker/PrettyPrint.hs:91:25: error: Not in scope: 'fail'

### ISSUE THREAD

**Issue by mrueg** [hadolint/language-docker#29]
Trying to build  4.0.1 here with ghc 8.0.1, and seeing this issue:

```
./setup build
Building language-docker-4.0.1...
Preprocessing library language-docker-4.0.1...
[ 1 of 11] Compiling Paths_language_docker ( dist/build/autogen/Paths_language_docker.hs, dist/build/Paths_language_docker.o )
[ 2 of 11] Compiling Language.Docker.Syntax ( src/Language/Docker/Syntax.hs, dist/build/Language/Docker/Syntax.o )
[ 3 of 11] Compiling Language.Docker.Syntax.Lift ( src/Language/Docker/Syntax/Lift.hs, dist/build/Language/Docker/Syntax/Lift.o )
[ 4 of 11] Compiling Language.Docker.PrettyPrint ( src/Language/Docker/PrettyPrint.hs, dist/build/Language/Docker/PrettyPrint.o )

src/Language/Docker/PrettyPrint.hs:91:25: error:
    Not in scope: ‘fail’
    Perhaps you want to add ‘fail’ to the import list in the import of
    ‘Prelude’ (src/Language/Docker/PrettyPrint.hs:(15,1)-(17,18)).
[ 5 of 11] Compiling Language.Docker.Normalize ( src/Language/Docker/Normalize.hs, dist/build/Language/Docker/Normalize.o )
[ 6 of 11] Compiling Language.Docker.Lexer ( src/Language/Docker/Lexer.hs, dist/build/Language/Docker/Lexer.o )
[ 7 of 11] Compiling Language.Docker.Parser ( src/Language/Docker/Parser.hs, dist/build/Language/Docker/Parser.o )
[ 8 of 11] Compiling Language.Docker.EDSL.Types ( src/Language/Docker/EDSL/Types.hs, dist/build/Language/Docker/EDSL/Types.o )
```

**Comment by lorenzo** [comment]
Do you want to send a patch to make it compile with 8.0? I was originally only goin to target 8.2 and above

**Comment by mrueg** [comment]
I'm not a haskell dev, more a package integrator, so it's unlikely to see a patch for that from me. :/ It would be great if the support for 8.0.x could be maintained.
